global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'omniflow-orders'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5000']
        labels:
          service: 'OrdersService'

  - job_name: 'omniflow-payments'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5001']
        labels:
          service: 'PaymentsService'
