---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  namespace: yath
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
      - name: seq
        image: datalust/seq:latest
        ports:
        - containerPort: 5341
          name: ingestion
        - containerPort: 80
          name: ui
        env:
        - name: ACCEPT_EULA
          value: "Y"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: seq
  namespace: yath
spec:
  selector:
    app: seq
  ports:
  - name: ingestion
    port: 5341
    targetPort: 5341
  - name: ui
    port: 80
    targetPort: 80
  type: ClusterIP
